services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      # - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api=true"
      # Docker integration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # HTTPS config
      - "--entryPoints.websecure.address=:443"
      # Set TLS certificate resolver for 'websecure' entrypoint (no need to specify manually)
      - "--entryPoints.websecure.http.tls.certresolver=myresolver"
      # TLS challenge does not work with Cloudflare proxy, use HTTP
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=m.mnich@proton.me"
      # Use dummy certificate server
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # Store ACME data in Docker volume
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # HTTP config
      - "--entrypoints.web.address=:80"
      # Redirect HTTP traffic to HTTPS ('web' to 'websecure')
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    labels:
      # Traefik API/dashboard integration
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.incognito-biuro.pl`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$bf.M.U31$1ElfChCQvtiz9seltbD/K/"
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`incognito-biuro.pl`) || Host(`www.incognito-biuro.pl`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
volumes:
  letsencrypt:
  wordpress:
